command_timeout = 500

add_newline = false
# A minimal left prompt
format = """${custom.parent_dir}$directory$character"""
palette = "wormbytes"
# move the rest of the prompt to the right
right_format = """$git_branch$git_status$dotnet$ruby$cmd_duration"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 1
truncate_to_repo = false
style = "bold blue"

[git_branch]
style = "bold magenta"

[git_status]
style = "bold orange"

[dotnet]
style = "bold blue"

[ruby]
style = "bold red"

[cmd_duration]
style = "bold yellow"

[custom.parent_dir]
command = "basename \"$(dirname \"$PWD\")\""
when = true
format = "\\[[$output](dimmed)\\] "

[palettes.wormbytes]
red = "#C7254E"
green = "#27761B"
yellow = "#A56C00"
blue = "#0366D6"
magenta = "#8250DF"
cyan = "#0884A8"
orange = "#C25D00"
fg = "#1C1C1C"
dim = "#858585"
comment = "#6B6B6B"
